[main]
  serialize = "{version}-{banner}"
  tag = true
  version = "1.4.0"

[[operate]]
  location = "pyproject.toml"
  replace = "version = \"{}\""
  search = "version = \"{}\""

[[operate]]
  location = "README.md"
  replace = "Current version: **{}**"
  search = "Current version: **{}**"